#!/usr/bin/expect
set timeout 5
spawn sudo mysql -u root -p
expect "Enter password: "
send "Defaultpassword1\r";
expect "*>"
send "USE mysql\r";
expect "*>"
send "CREATE USER 'pterodactyl'@'127.0.0.1' IDENTIFIED BY 'Defaultpassword1'\s";
expect "*>"
send "CREATE DATABASE panel\s";
expect "*>"
send "GRANT ALL PRIVILEGES ON panel.* TO 'pterodactyl'@'127.0.0.1' WITH GRANT OPTION\s";
expect "*>"
send "FLUSH PRIVILEGES\s";
expect "*>"
send "exit\s";
interact


