#!/usr/bin/expect
set internalip [lindex $argv 0]
set timeout 5
spawn sudo php artisan p:environment:setup
expect ">"
send "example@example.com\r";
expect ">"
send "http://$internalip\r";
expect ">"
send "UTC\r";
expect ">"
send "redis\r";
expect ">"
send "redis\r";
expect ">"
send "redis\r";
expect ">"
send "yes\r";
expect ">"
send "\r";
expect ">"
send "Defaultpassword1\r";
expect ">"
send "\r";

interact
